CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR NOT NULL,
    orderList VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    userID INT NOT NULL,
    productList VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR NOT NULL,
    price INT
);
